version: "3.8"

services:
  web:
    container_name: vue
    build: ./docker/vue
    ports:
      - 8080:8080
    privileged: true
    volumes:
      - ./app:/app:cached
    tty: true
    stdin_open: true
    command: /bin/sh
